package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Couponstatus generated by hbm2java
 */
public class Couponstatus implements java.io.Serializable {

	private int id;
	private String status;
	private Set coupons = new HashSet(0);

	public Couponstatus() {
	}

	public Couponstatus(int id, String status) {
		this.id = id;
		this.status = status;
	}

	public Couponstatus(int id, String status, Set coupons) {
		this.id = id;
		this.status = status;
		this.coupons = coupons;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getCoupons() {
		return this.coupons;
	}

	public void setCoupons(Set coupons) {
		this.coupons = coupons;
	}

}
