package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Coupon generated by hbm2java
 */
public class Coupon implements java.io.Serializable {

	private int id;
	private Offer offer;
	private Couponstatus couponstatus;
	private User user;
	private String code;
	private Set mapusercoupons = new HashSet(0);

	public Coupon() {
	}

	public Coupon(int id, Offer offer, Couponstatus couponstatus, String code) {
		this.id = id;
		this.offer = offer;
		this.couponstatus = couponstatus;
		this.code = code;
	}

	public Coupon(int id, Offer offer, Couponstatus couponstatus, User user,
			String code, Set mapusercoupons) {
		this.id = id;
		this.offer = offer;
		this.couponstatus = couponstatus;
		this.user = user;
		this.code = code;
		this.mapusercoupons = mapusercoupons;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Offer getOffer() {
		return this.offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}

	public Couponstatus getCouponstatus() {
		return this.couponstatus;
	}

	public void setCouponstatus(Couponstatus couponstatus) {
		this.couponstatus = couponstatus;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Set getMapusercoupons() {
		return this.mapusercoupons;
	}

	public void setMapusercoupons(Set mapusercoupons) {
		this.mapusercoupons = mapusercoupons;
	}

}
