package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Loyaltypoint generated by hbm2java
 */
public class Loyaltypoint implements java.io.Serializable {

	private Integer id;
	private Place place;
	private String rule;
	private String description;
	private Date startTime;
	private Date endTime;
	private int points;
	private boolean isActive;
	private Date createdOn;
	private Integer createdBy;
	private Date updatedOn;
	private Integer updatedBy;
	private Set maployaltypointusers = new HashSet(0);

	public Loyaltypoint() {
	}

	public Loyaltypoint(String rule, int points, boolean isActive) {
		this.rule = rule;
		this.points = points;
		this.isActive = isActive;
	}

	public Loyaltypoint(Place place, String rule, String description,
			Date startTime, Date endTime, int points, boolean isActive,
			Date createdOn, Integer createdBy, Date updatedOn,
			Integer updatedBy, Set maployaltypointusers) {
		this.place = place;
		this.rule = rule;
		this.description = description;
		this.startTime = startTime;
		this.endTime = endTime;
		this.points = points;
		this.isActive = isActive;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.updatedOn = updatedOn;
		this.updatedBy = updatedBy;
		this.maployaltypointusers = maployaltypointusers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Place getPlace() {
		return this.place;
	}

	public void setPlace(Place place) {
		this.place = place;
	}

	public String getRule() {
		return this.rule;
	}

	public void setRule(String rule) {
		this.rule = rule;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public int getPoints() {
		return this.points;
	}

	public void setPoints(int points) {
		this.points = points;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set getMaployaltypointusers() {
		return this.maployaltypointusers;
	}

	public void setMaployaltypointusers(Set maployaltypointusers) {
		this.maployaltypointusers = maployaltypointusers;
	}

}
