package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Loyaltyredeemprize generated by hbm2java
 */
public class Loyaltyredeemprize implements java.io.Serializable {

	private int id;
	private String loyaltyRedeemPrize;
	private Date createdOn;
	private Integer createdBy;
	private Date updatedOn;
	private Integer updatedBy;

	public Loyaltyredeemprize() {
	}

	public Loyaltyredeemprize(int id) {
		this.id = id;
	}

	public Loyaltyredeemprize(int id, String loyaltyRedeemPrize,
			Date createdOn, Integer createdBy, Date updatedOn, Integer updatedBy) {
		this.id = id;
		this.loyaltyRedeemPrize = loyaltyRedeemPrize;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.updatedOn = updatedOn;
		this.updatedBy = updatedBy;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLoyaltyRedeemPrize() {
		return this.loyaltyRedeemPrize;
	}

	public void setLoyaltyRedeemPrize(String loyaltyRedeemPrize) {
		this.loyaltyRedeemPrize = loyaltyRedeemPrize;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

}
