package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Maployaltypointuser generated by hbm2java
 */
public class Maployaltypointuser implements java.io.Serializable {

	private Integer id;
	private User user;
	private Loyaltypoint loyaltypoint;
	private Integer count;
	private Date createdOn;

	public Maployaltypointuser() {
	}

	public Maployaltypointuser(User user, Loyaltypoint loyaltypoint) {
		this.user = user;
		this.loyaltypoint = loyaltypoint;
	}

	public Maployaltypointuser(User user, Loyaltypoint loyaltypoint,
			Integer count, Date createdOn) {
		this.user = user;
		this.loyaltypoint = loyaltypoint;
		this.count = count;
		this.createdOn = createdOn;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Loyaltypoint getLoyaltypoint() {
		return this.loyaltypoint;
	}

	public void setLoyaltypoint(Loyaltypoint loyaltypoint) {
		this.loyaltypoint = loyaltypoint;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

}
