package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Mappeople generated by hbm2java
 */
public class Mappeople implements java.io.Serializable {

	private int id;
	private Peoplestatustype peoplestatustype;
	private User userByPeopleId;
	private User userByUserId;
	private Boolean isEnabled;
	private Date createdOn;
	private Date updatedOn;
	private Integer updatedBy;

	public Mappeople() {
	}

	public Mappeople(int id) {
		this.id = id;
	}

	public Mappeople(int id, Peoplestatustype peoplestatustype,
			User userByPeopleId, User userByUserId, Boolean isEnabled,
			Date createdOn, Date updatedOn, Integer updatedBy) {
		this.id = id;
		this.peoplestatustype = peoplestatustype;
		this.userByPeopleId = userByPeopleId;
		this.userByUserId = userByUserId;
		this.isEnabled = isEnabled;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
		this.updatedBy = updatedBy;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Peoplestatustype getPeoplestatustype() {
		return this.peoplestatustype;
	}

	public void setPeoplestatustype(Peoplestatustype peoplestatustype) {
		this.peoplestatustype = peoplestatustype;
	}

	public User getUserByPeopleId() {
		return this.userByPeopleId;
	}

	public void setUserByPeopleId(User userByPeopleId) {
		this.userByPeopleId = userByPeopleId;
	}

	public User getUserByUserId() {
		return this.userByUserId;
	}

	public void setUserByUserId(User userByUserId) {
		this.userByUserId = userByUserId;
	}

	public Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

}
