package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.OneToMany;

/**
 * Mapplacecategory generated by hbm2java
 */
public class Mapplacecategory implements java.io.Serializable {

	private Integer id;
	@OneToMany
	private Placecategory placecategory;
	private Place place;
	private Date createdOn;
	private Integer createdBy;

	public Mapplacecategory() {
	}

	public Mapplacecategory(int id) {
		this.id = id;
	}

	public Mapplacecategory(int id, Placecategory placecategory, Place place,
			Date createdOn, Integer createdBy) {
		this.id = id;
		this.placecategory = placecategory;
		this.place = place;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Placecategory getPlacecategory() {
		return this.placecategory;
	}

	public void setPlacecategory(Placecategory placecategory) {
		this.placecategory = placecategory;
	}

	public Place getPlace() {
		return this.place;
	}

	public void setPlace(Place place) {
		this.place = place;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

}
