package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Mapreview generated by hbm2java
 */
public class Mapreview  implements Serializable{

	private int id;
	private String review;
	@JsonIgnore
	private Reviewtype reviewtype;
	/*@JsonIgnoreProperties({"usertype","userstatus","place","settings","mappeoplesForUserId","maployaltypointusers",
		"mappeoplesForPeopleId","mapfavourites","mapreviews","coupons","mapusercoupons"})*/
	
	private User user;
	private Integer entityId;
	
	private Date createdOn;
	private Date updatedOn;
	private Integer updatedBy;

	public Mapreview() {
	}

	public Mapreview(int id) {
		this.id = id;
	}

	public Mapreview(int id, Reviewtype reviewtype, User user,
			Integer entityId, String review, Date createdOn, Date updatedOn,
			Integer updatedBy) {
		this.id = id;
		this.reviewtype = reviewtype;
		this.user = user;
		this.entityId = entityId;
		this.review = review;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
		this.updatedBy = updatedBy;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Reviewtype getReviewtype() {
		return this.reviewtype;
	}

	public void setReviewtype(Reviewtype reviewtype) {
		this.reviewtype = reviewtype;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	public String getReview() {
		return this.review;
	}

	public void setReview(String review) {
		this.review = review;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

}
