package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Mapuserloyaltyredeem generated by hbm2java
 */
public class Mapuserloyaltyredeem implements java.io.Serializable {

	private int id;
	private Integer userId;
	private Integer loyaltypointPrizeId;
	private Date createdOn;
	private Integer createdBy;
	private Date updatedOn;
	private Integer updatedBy;

	public Mapuserloyaltyredeem() {
	}

	public Mapuserloyaltyredeem(int id) {
		this.id = id;
	}

	public Mapuserloyaltyredeem(int id, Integer userId,
			Integer loyaltypointPrizeId, Date createdOn, Integer createdBy,
			Date updatedOn, Integer updatedBy) {
		this.id = id;
		this.userId = userId;
		this.loyaltypointPrizeId = loyaltypointPrizeId;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.updatedOn = updatedOn;
		this.updatedBy = updatedBy;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getLoyaltypointPrizeId() {
		return this.loyaltypointPrizeId;
	}

	public void setLoyaltypointPrizeId(Integer loyaltypointPrizeId) {
		this.loyaltypointPrizeId = loyaltypointPrizeId;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

}
