package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Offer generated by hbm2java
 */
public class Offer implements java.io.Serializable {

	private Integer id;
	@JsonIgnore
	private Offertype offertype;
	@JsonIgnore
	private Offerstatus offerstatus;
	//@JsonIgnore
	private Productcategory productcategory;
	//@JsonIgnore
	private Place place;
	private String name;
	private Integer discount;
	private Date validity;
	private Date validFrom;
	private String productCatImg;
	private String productName;
	private String description;
	@JsonIgnore
	private byte[] imgFile;
	private Date createdOn;
	private Integer createdBy;
	private Date updatedOn;
	private Integer updatedBy;
	private Boolean isActive;
	@JsonIgnore
	private Set coupons = new HashSet(0);

	public Offer() {
	}

	public Offer(String name) {
		this.name = name;
	}

	public Offer(Offertype offertype, Offerstatus offerstatus,
			Productcategory productcategory, Place place, String name,
			Integer discount, Date validity, Date validFrom, String productCatImg,
			String productName, String description, byte[] imgFile,
			Date createdOn, Integer createdBy, Date updatedOn,
			Integer updatedBy, Boolean isActive, Set coupons) {
		this.offertype = offertype;
		this.offerstatus = offerstatus;
		this.productcategory = productcategory;
		this.place = place;
		this.name = name;
		this.discount = discount;
		this.validity = validity;
		this.validFrom = validFrom;
		this.productCatImg = productCatImg;
		this.productName = productName;
		this.description = description;
		this.imgFile = imgFile;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.updatedOn = updatedOn;
		this.updatedBy = updatedBy;
		this.isActive = isActive;
		this.coupons = coupons;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Offertype getOffertype() {
		return this.offertype;
	}

	public void setOffertype(Offertype offertype) {
		this.offertype = offertype;
	}

	public Offerstatus getOfferstatus() {
		return this.offerstatus;
	}

	public void setOfferstatus(Offerstatus offerstatus) {
		this.offerstatus = offerstatus;
	}

	public Productcategory getProductcategory() {
		return this.productcategory;
	}

	public void setProductcategory(Productcategory productcategory) {
		this.productcategory = productcategory;
	}

	public Place getPlace() {
		return this.place;
	}

	public void setPlace(Place place) {
		this.place = place;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getDiscount() {
		return this.discount;
	}

	public void setDiscount(Integer discount) {
		this.discount = discount;
	}

	public Date getValidity() {
		return this.validity;
	}

	public void setValidity(Date validity) {
		this.validity = validity;
	}

	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	public String getProductCatImg() {
		return this.productCatImg;
	}

	public void setProductCatImg(String productCatImg) {
		this.productCatImg = productCatImg;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public byte[] getImgFile() {
		return this.imgFile;
	}

	public void setImgFile(byte[] imgFile) {
		this.imgFile = imgFile;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set getCoupons() {
		return this.coupons;
	}

	public void setCoupons(Set coupons) {
		this.coupons = coupons;
	}

}
