package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Offerstatus generated by hbm2java
 */
public class Offerstatus implements java.io.Serializable {

	private int id;
	private String status;
	private Set offers = new HashSet(0);

	public Offerstatus() {
	}

	public Offerstatus(int id, String status) {
		this.id = id;
		this.status = status;
	}

	public Offerstatus(int id, String status, Set offers) {
		this.id = id;
		this.status = status;
		this.offers = offers;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getOffers() {
		return this.offers;
	}

	public void setOffers(Set offers) {
		this.offers = offers;
	}

}
