package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Peoplestatustype generated by hbm2java
 */
public class Peoplestatustype implements java.io.Serializable {

	private int id;
	private String statusType;
	private Set mappeoples = new HashSet(0);

	public Peoplestatustype() {
	}

	public Peoplestatustype(int id) {
		this.id = id;
	}

	public Peoplestatustype(int id, String statusType, Set mappeoples) {
		this.id = id;
		this.statusType = statusType;
		this.mappeoples = mappeoples;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getStatusType() {
		return this.statusType;
	}

	public void setStatusType(String statusType) {
		this.statusType = statusType;
	}

	public Set getMappeoples() {
		return this.mappeoples;
	}

	public void setMappeoples(Set mappeoples) {
		this.mappeoples = mappeoples;
	}

}
