package com.ubilink.model;

import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Placecategory generated by hbm2java
 */
public class Placecategory implements java.io.Serializable {

	private Integer id;
	private String category;
	private String displayCategory;
	@JsonIgnore
	private Blob categoryImg;
	private Boolean isApplicable;
	@JsonIgnore
	private Set mapplacecategories = new HashSet(0);

	public Placecategory() {
	}

	public Placecategory(String category) {
		this.category = category;
	}

	public Placecategory(String category, Blob categoryImg,
			Boolean isApplicable, Set mapplacecategories) {
		this.category = category;
		this.categoryImg = categoryImg;
		this.isApplicable = isApplicable;
		this.mapplacecategories = mapplacecategories;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Blob getCategoryImg() {
		return this.categoryImg;
	}

	public void setCategoryImg(Blob categoryImg) {
		this.categoryImg = categoryImg;
	}

	public Boolean getIsApplicable() {
		return this.isApplicable;
	}

	public void setIsApplicable(Boolean isApplicable) {
		this.isApplicable = isApplicable;
	}

	public Set getMapplacecategories() {
		return this.mapplacecategories;
	}

	public void setMapplacecategories(Set mapplacecategories) {
		this.mapplacecategories = mapplacecategories;
	}

	public String getDisplayCategory() {
		return this.displayCategory;
	}

	public void setDisplayCategory(String displayCategory) {
		this.displayCategory = displayCategory;
	}

	

}
