package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.mysql.cj.jdbc.Blob;

/**
 * Productcategory generated by hbm2java
 */

public class Productcategory implements java.io.Serializable {

	private int id;
	private String category;
	@JsonIgnore
	private Blob productCatImg;
	@JsonIgnore
	private Set offers = new HashSet(0);

	public Productcategory() {
	}

	public Productcategory(int id, String category) {
		this.id = id;
		this.category = category;
	}

	public Productcategory(int id, String category, Blob productCatImg, Set offers) {
		this.id = id;
		this.category = category;
		this.setProductCatImg(productCatImg);
		this.offers = offers;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}


	public Set getOffers() {
		return this.offers;
	}

	public void setOffers(Set offers) {
		this.offers = offers;
	}

	public Blob getProductCatImg() {
		return this.productCatImg;
	}

	public void setProductCatImg(Blob productCatImg) {
		this.productCatImg = productCatImg;
	}

}
