package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reminder generated by hbm2java
 */
public class Reminder implements java.io.Serializable {

	private int id;
	private Date time;
	private String message;
	private String type;
	private Set mapfavourites = new HashSet(0);

	public Reminder() {
	}

	public Reminder(int id, Date time, String message) {
		this.id = id;
		this.time = time;
		this.message = message;
	}

	public Reminder(int id, Date time, String message, String type,
			Set mapfavourites) {
		this.id = id;
		this.time = time;
		this.message = message;
		this.type = type;
		this.mapfavourites = mapfavourites;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getMapfavourites() {
		return this.mapfavourites;
	}

	public void setMapfavourites(Set mapfavourites) {
		this.mapfavourites = mapfavourites;
	}

}
