package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Reviewtype generated by hbm2java
 */
public class Reviewtype implements java.io.Serializable {

	private int id;
	private String type;
	private Set mapreviews = new HashSet(0);

	public Reviewtype() {
	}

	public Reviewtype(int id) {
		this.id = id;
	}

	public Reviewtype(int id, String type, Set mapreviews) {
		this.id = id;
		this.type = type;
		this.mapreviews = mapreviews;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getMapreviews() {
		return this.mapreviews;
	}

	public void setMapreviews(Set mapreviews) {
		this.mapreviews = mapreviews;
	}

}
