package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Usermode generated by hbm2java
 */
public class Usermode implements java.io.Serializable {

	private int id;
	private String userMode;
	private Set settings = new HashSet(0);

	public Usermode() {
	}

	public Usermode(int id) {
		this.id = id;
	}

	public Usermode(int id, String userMode, Set settings) {
		this.id = id;
		this.userMode = userMode;
		this.settings = settings;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUserMode() {
		return this.userMode;
	}

	public void setUserMode(String userMode) {
		this.userMode = userMode;
	}

	public Set getSettings() {
		return this.settings;
	}

	public void setSettings(Set settings) {
		this.settings = settings;
	}

}
