package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Userstatus generated by hbm2java
 */
public class Userstatus implements java.io.Serializable {

	private int id;
	private String status;
	private Set users = new HashSet(0);

	public Userstatus() {
	}

	public Userstatus(int id, String status) {
		this.id = id;
		this.status = status;
	}

	public Userstatus(int id, String status, Set users) {
		this.id = id;
		this.status = status;
		this.users = users;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
