package com.ubilink.model;

// Generated 26 Apr, 2014 4:44:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Usertype generated by hbm2java
 */
public class Usertype implements java.io.Serializable {

	private int id;
	private String type;
	private Set users = new HashSet(0);

	public Usertype() {
	}

	public Usertype(int id, String type) {
		this.id = id;
		this.type = type;
	}

	public Usertype(int id, String type, Set users) {
		this.id = id;
		this.type = type;
		this.users = users;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
